const U='https://aufsewqtybpothlrsjij.supabase.co';
const K='sb_publishable_Xh-qzcyJY0-IzHHgri8XNw_f00aJ_sP';
const PROD_ORIGIN='https://www.votofortearapongas.com.br';
const APP_ORIGIN=location.hostname.endsWith('.vercel.app')?location.origin:PROD_ORIGIN;
let c;
export async function client(){if(c)return c;const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');c=m.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return c}
export async function profile(){const s=await client();const{data:{user},error}=await s.auth.getUser();if(error||!user)return null;const{data:p,error:pe}=await s.from('perfis_usuarios').select('id,nome,email,role,ativo,troca_senha_obrigatoria,acesso_global').eq('id',user.id).maybeSingle();if(pe||!p||p.ativo===false)return null;return p}
export async function currentUser(){try{const s=await client();const{data,error}=await s.auth.getUser();if(error||!data?.user)return null;const p=await profile();if(!p){await s.auth.signOut();return null}return Object.assign({},data.user,{vfProfile:p})}catch(e){console.error('Auth gate:',e);return null}}
function deviceLabel(){const ua=navigator.userAgent||'';if(/iPhone|iPad|iPod/i.test(ua))return 'iPhone / iPad';if(/Android/i.test(ua))return 'Android';if(/Mobile/i.test(ua))return 'Celular';return 'Computador'}
export async function auditEvent(tipo,acao,detalhes='',targetUserId=null,options={}){try{const s=await client();const{data:{user},error}=await s.auth.getUser();if(error||!user)return false;const target=targetUserId?String(targetUserId):user.id;const actorTarget=target!==user.id;const seconds=Number(options.dedupeSeconds==null?4:options.dedupeSeconds);if(seconds>0){const since=new Date(Date.now()-seconds*1000).toISOString();const{data:recent}=await s.from('audit_logs').select('id').eq('user_id',target).eq('tipo',String(tipo||'sistema')).eq('acao',String(acao||'Atividade')).gte('criado_em',since).limit(1);if(recent&&recent.length)return false}const row={user_id:target,tipo:String(tipo||'sistema'),acao:String(acao||'Atividade'),detalhes:String(detalhes||'')||null,dispositivo:deviceLabel(),actor_user_id:actorTarget?user.id:null,target_user_id:actorTarget?target:null};const{error:ie}=await s.from('audit_logs').insert(row);if(ie){console.warn('Auditoria:',ie);return false}return true}catch(e){console.warn('Auditoria:',e);return false}}
export async function requireAuth(){const u=await currentUser();if(!u){location.replace(APP_ORIGIN+'/?login=1');return null}if(u.vfProfile?.troca_senha_obrigatoria&&!location.pathname.endsWith('/force-password.html')){location.replace(APP_ORIGIN+'/force-password.html');return null}return u}
export async function signIn(email,password){const s=await client();const clean=String(email||'').trim().toLowerCase();const{error}=await s.auth.signInWithPassword({email:clean,password:String(password||'')});if(error)throw new Error('E-mail ou senha inválidos.');const u=await currentUser();if(!u)throw new Error('Perfil de acesso inválido ou inativo.');await auditEvent('login','Autenticacao realizada','Login seguro para '+(u.vfProfile?.email||clean),null,{dedupeSeconds:8});return u}
export async function requestPasswordReset(email){const s=await client();const clean=String(email||'').trim().toLowerCase();if(!clean)throw new Error('Informe seu e-mail cadastrado.');const{error}=await s.rpc('request_managed_password_reset_v2',{target_email:clean});if(error)throw error;return true}
export async function updatePassword(password){const v=String(password||'');if(v.length<8)throw new Error('A nova senha deve ter pelo menos 8 caracteres.');const s=await client();const{data,error}=await s.auth.getUser();if(error||!data?.user)throw new Error('Sua sessão expirou. Entre novamente com a senha temporária.');const{error:ue}=await s.auth.updateUser({password:v});if(ue)throw ue;const{error:re}=await s.rpc('complete_managed_password_change_v2');if(re)throw re;return true}
export async function adminAction(action,payload={}){const s=await client();const{data,error}=await s.functions.invoke('admin-user-management',{body:Object.assign({action},payload)});if(error)throw error;if(data?.error)throw new Error(data.error);try{if(action==='create_user'&&data?.user?.id){await auditEvent('usuario','Usuario criado',(data.user.nome||payload.nome||data.user.email||payload.email||'Novo usuario')+' • perfil '+(data.user.role||payload.role||'usuario'),data.user.id,{dedupeSeconds:2})}else if(action==='reset_password'&&payload.user_id){await auditEvent('senha','Senha temporaria definida','Redefinicao administrativa para '+(data?.user?.nome||data?.user?.email||payload.user_id),payload.user_id,{dedupeSeconds:2})}else if(action==='set_active'&&payload.user_id){await auditEvent('usuario',payload.ativo?'Usuario ativado':'Usuario desativado','Alteracao administrativa de acesso',payload.user_id,{dedupeSeconds:2})}}catch(_){}return data}
export async function signOut(){const s=await client();try{const{data:{user}}=await s.auth.getUser();if(user)await auditEvent('login','Logout realizado','Sessao encerrada pelo usuario',null,{dedupeSeconds:3})}catch(_){}await s.auth.signOut();location.replace(APP_ORIGIN+'/?login=1')}
export function route(user){const u=user||null;if(u?.vfProfile?.troca_senha_obrigatoria){location.replace(APP_ORIGIN+'/force-password.html');return}const m=/Mobile|Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(max-width:900px)').matches;location.replace(APP_ORIGIN+(m?'/mobile-production.html':'/desktop-production.html'))}
