(async function(){
'use strict';
if(window.__vfDesktopV31)return;window.__vfDesktopV31=true;
if(window.matchMedia&&window.matchMedia('(max-width:900px)').matches)return;

var auth;try{auth=await import('./auth-gate.js');}catch(e){console.warn('Desktop v31 auth',e);return;}
var user=await auth.currentUser();if(!user)return;
var profile=user.vfProfile||{},role=String(profile.role||'');
var isAdmin=role==='master'||role==='adm';
var users=[],requests=[],audit=[],leaderCount=0,auditCount=0,leaders=[];
var originalSwitch=null,currentView='map';

function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c;});}
function firstName(){return String(profile.nome||user.email||'Usuário').trim().split(/\s+/)[0];}
function initials(){var p=String(profile.nome||user.email||'?').trim().split(/\s+/).filter(Boolean);return ((p[0]||'?')[0]+(p.length>1?p[p.length-1][0]:'')).toUpperCase();}
function roleLabel(){return role==='master'?'Master':role==='adm'?'Administrador':'Usuário';}
function icon(n){var m={home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5M5.5 10.5V20h13v-9.5M9.5 20v-6h5v6"/></svg>',map:'<svg viewBox="0 0 24 24"><path d="M3 6.5l5-2.5 8 3 5-2.5v13L16 20l-8-3-5 2.5zM8 4v13M16 7v13"/></svg>',school:'<svg viewBox="0 0 24 24"><path d="M3 10l9-5 9 5-9 5zM7 13v5c3 1.8 7 1.8 10 0v-5M21 10v7"/></svg>',people:'<svg viewBox="0 0 24 24"><path d="M16 20v-1.5a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4V20M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM19 8v6M22 11h-6"/></svg>',compass:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M15.5 8.5l-2 5-5 2 2-5z"/></svg>',users:'<svg viewBox="0 0 24 24"><path d="M15 20v-1.5a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4V20M8 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8M19 8v6M22 11h-6"/></svg>',key:'<svg viewBox="0 0 24 24"><circle cx="8" cy="15" r="4"/><path d="m11 12 9-9M17 6l3 3M14 9l3 3"/></svg>',audit:'<svg viewBox="0 0 24 24"><path d="M7 3h10v4H7zM5 5H3v16h18V5h-2M7 12h10M7 16h7"/></svg>',wa:'<svg viewBox="0 0 24 24"><path d="M21 11.5a8.5 8.5 0 0 1-12.3 7.6L3 21l1.9-5.7A8.5 8.5 0 1 1 21 11.5z"/></svg>'};return m[n]||m.home;}
function viewInfo(v){return {map:['Mapa eleitoral','Visão territorial, colégios e lideranças'],colegios:['Colégios eleitorais','Locais de votação e informações eleitorais'],liderancas:['Lideranças','Relacionamento e gerenciamento de lideranças'],distritos:['Distritos','Distribuição territorial e responsáveis'],admin:['Visão Geral','Painel Administrativo do VotoForte']}[v]||['VotoForte Arapongas','Sistema eleitoral'];}
function invalidateMap(){setTimeout(function(){try{if(typeof map!=='undefined'&&map&&map.invalidateSize)map.invalidateSize();else if(window.map&&window.map.invalidateSize)window.map.invalidateSize();}catch(_){}},120);}

function buildShell(){
 var root=document.getElementById('app-root'),workspace=document.querySelector('.workspace-main');if(!root||!workspace||document.getElementById('vf-desktop-sidebar'))return false;
 document.body.classList.add('vf-desktop-v31');
 var main=document.createElement('div');main.className='vf-desktop-main';
 var header=document.createElement('div');header.id='vf-desktop-header';header.innerHTML='<div class="vf-d-head-copy"><h1 id="vf-d-view-title">Mapa eleitoral</h1><p id="vf-d-view-sub">Visão territorial, colégios e lideranças</p></div><div class="vf-d-head-actions" id="vf-d-head-actions"></div>';
 workspace.parentNode.insertBefore(main,workspace);main.appendChild(header);main.appendChild(workspace);
 var side=document.createElement('aside');side.id='vf-desktop-sidebar';
 side.innerHTML='<div class="vf-d-brand"><div class="vf-d-brand-flag"><img src="assets/bandeira_arapongas.png" alt=""></div><div class="vf-d-brand-copy"><strong>VotoForte Arapongas</strong><span>Mapa & Gestão Eleitoral</span></div></div><div class="vf-d-sidebar-scroll" id="vf-d-side-scroll"></div><div class="vf-d-account"><div class="vf-d-account-card"><div class="vf-d-avatar">'+esc(initials())+'</div><div class="vf-d-account-copy"><strong>'+esc(profile.nome||user.email)+'</strong><span>'+esc(roleLabel())+'</span></div><button class="vf-d-account-menu" id="vf-d-account-profile" title="Minha conta">›</button></div><div class="vf-d-account-actions"><button id="vf-d-change-pass">Alterar senha</button><button id="vf-d-logout">Sair</button></div></div>';
 root.appendChild(side);
 buildNav();moveHeaderControls();bindAccount();hookSwitch();
 if(isAdmin){buildAdminHome(workspace);buildAdminDialogs();showAdminHome();loadAdminData();}else{setView('map',false);}
 setTimeout(invalidateMap,300);return true;
}

function buildNav(){
 var scroll=document.getElementById('vf-d-side-scroll');if(!scroll)return;
 var html='';
 if(isAdmin)html+='<section class="vf-d-nav-section"><div class="vf-d-nav-label">Administração</div><div class="vf-d-nav" id="vf-d-admin-nav"><button data-admin="home">'+icon('home')+'<span>Visão Geral</span></button><button data-admin="users">'+icon('users')+'<span>Usuários</span></button><button data-admin="requests">'+icon('key')+'<span>Solicitações</span><b class="vf-d-nav-count" id="vf-d-req-count">0</b></button><button data-admin="audit">'+icon('audit')+'<span>Auditoria</span></button></div></section>';
 html+='<section class="vf-d-nav-section"><div class="vf-d-nav-label">Operação</div><div class="vf-d-nav" id="vf-d-op-nav"><button data-view="map">'+icon('map')+'<span>Mapa</span></button><button data-view="colegios">'+icon('school')+'<span>Colégios</span></button><button data-view="liderancas">'+icon('people')+'<span>Lideranças</span></button><button data-view="distritos">'+icon('compass')+'<span>Distritos</span></button></div></section><section class="vf-d-nav-section"><div class="vf-d-nav-label">Ação rápida</div><div class="vf-d-nav"><button class="vf-d-whatsapp" id="vf-d-wa-nav">'+icon('wa')+'<span>WhatsApp</span></button></div></section>';
 scroll.innerHTML=html;
 scroll.querySelectorAll('[data-view]').forEach(function(b){b.onclick=function(){setView(b.dataset.view,true);};});
 scroll.querySelectorAll('[data-admin]').forEach(function(b){b.onclick=function(){var a=b.dataset.admin;if(a==='home')showAdminHome();else openAdminDialog(a);};});
 var wa=document.getElementById('vf-d-wa-nav');if(wa)wa.onclick=openWhatsAppDialog;
}

function moveHeaderControls(){
 var box=document.getElementById('vf-d-head-actions');if(!box)return;
 var layers=document.querySelector('header.topbar .layers-box-compact'),cand=document.querySelector('header.topbar #cand-select'),vereador=document.querySelector('header.topbar #filter-liderancas-vereador'),add=document.querySelector('header.topbar .btn-topbar-primary');
 [layers,cand,vereador,add].forEach(function(n){if(n)box.appendChild(n);});
 var wa=document.createElement('button');wa.type='button';wa.className='vf-d-head-wa';wa.innerHTML=icon('wa')+'<span>WhatsApp</span>';wa.onclick=openWhatsAppDialog;box.appendChild(wa);
}

function bindAccount(){
 var p=document.getElementById('vf-d-account-profile'),cp=document.getElementById('vf-d-change-pass'),lo=document.getElementById('vf-d-logout');
 if(p)p.onclick=function(){try{if(typeof window.switchView==='function')window.switchView('users');else if(typeof window.openModal==='function')window.openModal('modal-switch-user');}catch(_){}};
 if(cp)cp.onclick=function(){try{if(typeof window.openModal==='function')window.openModal('modal-change-password');}catch(_){}};
 if(lo)lo.onclick=async function(){if(!confirm('Deseja realmente sair da sua conta?'))return;await auth.signOut();};
}

function hookSwitch(){
 if(originalSwitch||typeof window.switchView!=='function')return;
 originalSwitch=window.switchView;
 window.switchView=function(v){hideAdminHome();currentView=v||'map';updateNav();updateHeader();var r=originalSwitch.apply(this,arguments);invalidateMap();return r;};
}
function setView(v,call){hideAdminHome();currentView=v;updateNav();updateHeader();if(call!==false&&typeof window.switchView==='function')window.switchView(v);invalidateMap();}
function updateNav(){document.querySelectorAll('#vf-d-op-nav [data-view]').forEach(function(b){b.classList.toggle('active',b.dataset.view===currentView&&!document.body.classList.contains('vf-d-admin-home'));});document.querySelectorAll('#vf-d-admin-nav [data-admin]').forEach(function(b){b.classList.remove('active');});}
function updateHeader(){var x=viewInfo(currentView),h=document.getElementById('vf-d-view-title'),p=document.getElementById('vf-d-view-sub');if(h)h.textContent=x[0];if(p)p.textContent=x[1];}
function hideAdminHome(){document.body.classList.remove('vf-d-admin-home');}
function showAdminHome(){if(!isAdmin)return;document.body.classList.add('vf-d-admin-home');currentView='admin';var x=viewInfo('admin');document.getElementById('vf-d-view-title').textContent=x[0];document.getElementById('vf-d-view-sub').textContent=x[1];document.querySelectorAll('#vf-d-op-nav [data-view]').forEach(function(b){b.classList.remove('active');});document.querySelectorAll('#vf-d-admin-nav [data-admin]').forEach(function(b){b.classList.toggle('active',b.dataset.admin==='home');});loadAdminData();}

function buildAdminHome(workspace){
 if(document.getElementById('vf-desktop-admin-home'))return;
 var el=document.createElement('section');el.id='vf-desktop-admin-home';el.innerHTML='<div class="vf-d-admin-welcome"><div><div class="vf-d-admin-kicker">Gestão do sistema</div><h2>Olá, '+esc(firstName())+'</h2><p>Acompanhe acessos, usuários e atividades do VotoForte.</p></div><span class="vf-d-role-chip">'+esc(roleLabel().toUpperCase())+'</span></div><div class="vf-d-stats"><div class="vf-d-stat"><span>Usuários</span><strong id="vfDUsers">—</strong></div><div class="vf-d-stat warn"><span>Senhas pendentes</span><strong id="vfDReq">—</strong></div><div class="vf-d-stat ok"><span>Lideranças</span><strong id="vfDLeaders">—</strong></div><div class="vf-d-stat"><span>Atividades</span><strong id="vfDAudit">—</strong></div></div><div class="vf-d-grid-2"><div class="vf-d-panel"><div class="vf-d-panel-head"><h3>Administração</h3><span>Acesso ADM / Master</span></div><div class="vf-d-admin-actions"><button class="vf-d-admin-action primary" data-open-admin="create"><span class="ico">👤＋</span><strong>Novo usuário</strong><small>Criar conta, liberar acesso e definir senha temporária.</small></button><button class="vf-d-admin-action" data-open-admin="users"><span class="ico">👥</span><strong>Gerenciar usuários</strong><small>Contas, bloqueios e redefinição de senha.</small></button><button class="vf-d-admin-action alert" data-open-admin="requests"><span class="ico">🔑</span><strong>Solicitações <b class="vf-d-badge" id="vfDReqBadge">0</b></strong><small>Pedidos de ajuda feitos na tela de login.</small></button><button class="vf-d-admin-action" data-open-admin="audit"><span class="ico">📋</span><strong>Auditoria</strong><small>Movimentações recentes do sistema.</small></button></div></div><div class="vf-d-panel"><div class="vf-d-panel-head"><h3>Solicitações recentes</h3><span id="vfDReqHint">Atualizado</span></div><div class="vf-d-feed" id="vfDRecentReq"><div class="vf-d-empty">Carregando...</div></div><div class="vf-d-panel-head" style="margin-top:16px"><h3>Atividades recentes</h3><span>Auditoria</span></div><div class="vf-d-feed" id="vfDRecentAudit"><div class="vf-d-empty">Carregando...</div></div></div></div>';
 workspace.insertBefore(el,workspace.firstChild);el.querySelectorAll('[data-open-admin]').forEach(function(b){b.onclick=function(){openAdminDialog(b.dataset.openAdmin);};});
}

function dialog(id,title,body,small){var o=document.createElement('div');o.id=id;o.className='vf-d-dialog-overlay';o.innerHTML='<section class="vf-d-dialog'+(small?' small':'')+'"><div class="vf-d-dialog-head"><h3>'+title+'</h3><button class="vf-d-close" data-close>×</button></div>'+body+'</section>';document.body.appendChild(o);o.querySelector('[data-close]').onclick=function(){o.classList.remove('show');};o.onclick=function(e){if(e.target===o)o.classList.remove('show');};return o;}
function buildAdminDialogs(){
 if(document.getElementById('vf-d-create'))return;
 var roleOpts=role==='master'?'<option value="vereador">Usuário / Vereador</option><option value="adm">Administrador</option>':'<option value="vereador">Usuário / Vereador</option>';
 var c=dialog('vf-d-create','Novo usuário','<form id="vf-d-create-form"><div class="vf-d-form-grid"><div class="vf-d-field"><label>Nome</label><input id="vfDCNome" required></div><div class="vf-d-field"><label>E-mail</label><input id="vfDCEmail" type="email" required></div><div class="vf-d-field"><label>WhatsApp</label><input id="vfDCWhats" placeholder="(43) 99999-9999"></div><div class="vf-d-field"><label>Perfil</label><select id="vfDCRole">'+roleOpts+'</select></div><div class="vf-d-field full"><label>Senha temporária</label><input id="vfDCPass" type="password" minlength="8" required placeholder="Mínimo 8 caracteres"></div></div><button class="vf-d-save" id="vfDCSave">Criar e liberar acesso</button><div class="vf-d-status" id="vfDCStatus"></div></form>',true);c.querySelector('form').onsubmit=createUser;
 dialog('vf-d-users','Gerenciar usuários','<div style="display:flex;justify-content:flex-end;margin-bottom:8px"><button class="vf-d-save" style="margin:0" id="vfDNewFromList">＋ Novo usuário</button></div><div id="vfDUsersList"></div>');
 document.getElementById('vfDNewFromList').onclick=function(){openAdminDialog('create');};
 dialog('vf-d-requests','Solicitações de senha','<div id="vfDRequestsList"></div>');
 dialog('vf-d-audit','Auditoria recente','<div id="vfDAuditList"></div>');
}
function openAdminDialog(which){if(which==='create'){document.getElementById('vf-d-create').classList.add('show');return;}if(which==='users')renderUsers();if(which==='requests')renderRequests();if(which==='audit')renderAudit();var d=document.getElementById('vf-d-'+which);if(d)d.classList.add('show');}

async function createUser(e){e.preventDefault();var st=document.getElementById('vfDCStatus'),btn=document.getElementById('vfDCSave'),pass=document.getElementById('vfDCPass').value;if(pass.length<8){st.textContent='A senha precisa ter pelo menos 8 caracteres.';return;}btn.disabled=true;btn.textContent='Criando...';st.textContent='';st.className='vf-d-status';try{await auth.adminAction('create_user',{nome:document.getElementById('vfDCNome').value.trim(),email:document.getElementById('vfDCEmail').value.trim(),whatsapp:document.getElementById('vfDCWhats').value.trim(),role:document.getElementById('vfDCRole').value,password:pass,cargo:document.getElementById('vfDCRole').value==='adm'?'Administrador':'Usuário'});st.className='vf-d-status ok';st.textContent='Usuário criado. A senha é temporária e deverá ser trocada no primeiro acesso.';e.target.reset();await loadAdminData();}catch(err){st.textContent='Erro: '+(err.message||err);}finally{btn.disabled=false;btn.textContent='Criar e liberar acesso';}}
async function resetPassword(id,name){var p=prompt('Digite uma senha temporária para '+name+' (mínimo 8 caracteres):');if(!p)return;if(p.length<8){alert('A senha precisa ter pelo menos 8 caracteres.');return;}try{await auth.adminAction('reset_password',{user_id:id,password:p});alert('Senha temporária definida. O usuário deverá criar uma nova senha no próximo acesso.');await loadAdminData();renderUsers();renderRequests();}catch(e){alert('Não foi possível redefinir: '+(e.message||e));}}
async function toggleActive(id,name,active){if(!confirm((active?'Bloquear ':'Liberar ')+name+'?'))return;try{await auth.adminAction('set_active',{user_id:id,ativo:!active});await loadAdminData();renderUsers();}catch(e){alert('Não foi possível alterar o acesso: '+(e.message||e));}}
function renderUsers(){var box=document.getElementById('vfDUsersList');if(!box)return;box.innerHTML=users.length?users.map(function(x){return '<div class="vf-d-list-row"><div class="vf-d-list-copy"><strong>'+esc(x.nome||x.email)+'</strong><span>'+esc(x.email)+' • '+esc(x.role||'usuário')+' • '+(x.ativo===false?'bloqueado':'ativo')+(x.troca_senha_obrigatoria?' • troca de senha pendente':'')+'</span></div><div class="vf-d-row-actions"><button class="vf-d-row-btn" data-reset="'+esc(x.id)+'" data-name="'+esc(x.nome||x.email)+'">Nova senha</button><button class="vf-d-row-btn '+(x.ativo===false?'':'danger')+'" data-active="'+esc(x.id)+'" data-name="'+esc(x.nome||x.email)+'" data-current="'+(x.ativo!==false?'1':'0')+'">'+(x.ativo===false?'Liberar':'Bloquear')+'</button></div></div>';}).join(''):'<div class="vf-d-empty">Nenhum usuário encontrado.</div>';box.querySelectorAll('[data-reset]').forEach(function(b){b.onclick=function(){resetPassword(b.dataset.reset,b.dataset.name);};});box.querySelectorAll('[data-active]').forEach(function(b){b.onclick=function(){toggleActive(b.dataset.active,b.dataset.name,b.dataset.current==='1');};});}
function renderRequests(){var box=document.getElementById('vfDRequestsList');if(!box)return;box.innerHTML=requests.length?requests.map(function(x){var p=x.perfis_usuarios||{},n=p.nome||x.email;return '<div class="vf-d-list-row"><div class="vf-d-list-copy"><strong>'+esc(n)+'</strong><span>'+esc(x.email)+' • '+new Date(x.solicitado_em).toLocaleString('pt-BR')+'</span></div><button class="vf-d-row-btn" data-req="'+esc(x.user_id)+'" data-name="'+esc(n)+'">Redefinir senha</button></div>';}).join(''):'<div class="vf-d-empty">Nenhuma solicitação pendente.</div>';box.querySelectorAll('[data-req]').forEach(function(b){b.onclick=function(){resetPassword(b.dataset.req,b.dataset.name);};});}
function renderAudit(){var box=document.getElementById('vfDAuditList');if(!box)return;box.innerHTML=audit.length?audit.map(function(a){return '<div class="vf-d-list-row"><div class="vf-d-list-copy"><strong>'+esc(a.acao||a.tipo||'Atividade')+'</strong><span>'+new Date(a.criado_em).toLocaleString('pt-BR')+(a.detalhes?' • '+esc(a.detalhes):'')+'</span></div></div>';}).join(''):'<div class="vf-d-empty">Nenhuma atividade disponível.</div>';}
function renderAdminData(){function set(id,v){var e=document.getElementById(id);if(e)e.textContent=String(v);}set('vfDUsers',users.length);set('vfDReq',requests.length);set('vfDLeaders',leaderCount);set('vfDAudit',auditCount);set('vfDReqBadge',requests.length);set('vf-d-req-count',requests.length);var r=document.getElementById('vfDRecentReq');if(r)r.innerHTML=requests.length?requests.slice(0,3).map(function(x){var p=x.perfis_usuarios||{};return '<div class="vf-d-feed-row"><strong>'+esc(p.nome||x.email)+'</strong><span>'+new Date(x.solicitado_em).toLocaleString('pt-BR')+' • aguardando redefinição</span></div>';}).join(''):'<div class="vf-d-empty">Nenhuma solicitação pendente.</div>';var a=document.getElementById('vfDRecentAudit');if(a)a.innerHTML=audit.length?audit.slice(0,4).map(function(x){return '<div class="vf-d-feed-row"><strong>'+esc(x.acao||x.tipo||'Atividade')+'</strong><span>'+new Date(x.criado_em).toLocaleString('pt-BR')+(x.detalhes?' • '+esc(x.detalhes):'')+'</span></div>';}).join(''):'<div class="vf-d-empty">Nenhuma atividade disponível.</div>';renderUsers();renderRequests();renderAudit();}
async function loadAdminData(){if(!isAdmin)return;try{var c=await auth.client(),res=await Promise.all([auth.adminAction('list_users'),auth.adminAction('list_requests'),c.from('liderancas').select('id',{count:'exact',head:true}),c.from('audit_logs').select('id',{count:'exact',head:true}),c.from('audit_logs').select('tipo,acao,detalhes,criado_em').order('criado_em',{ascending:false}).limit(12)]);users=res[0].users||[];requests=res[1].requests||[];leaderCount=res[2].count||0;auditCount=res[3].count||0;audit=res[4].data||[];}catch(e){console.warn('Desktop admin data',e);}renderAdminData();}

/* WhatsApp mirrors approved mobile flow, adapted to desktop */
function digits(v){return String(v||'').replace(/\D/g,'');}function normalizeBR(v){var d=digits(v);if(!d)return'';if(d.length===10||d.length===11)d='55'+d;return d;}function template(kind,l){var n=String(l&&l.nome||'').trim().split(/\s+/)[0],ola=n?'Olá, '+n+'!':'Olá!';if(kind==='reuniao')return ola+' Tudo bem? Gostaria de alinhar uma reunião com você. Qual horário fica melhor?';if(kind==='convite')return ola+' Tudo bem? Quero te fazer um convite e contar com a sua participação. Posso te passar os detalhes?';if(kind==='lembrete')return ola+' Passando para lembrar do nosso compromisso combinado. Se precisar ajustar o horário, me avise por aqui.';if(kind==='agradecimento')return ola+' Muito obrigado pelo apoio e pela parceria. Seguimos juntos!';return'';}
async function loadLeaders(){try{var c=await auth.client(),r=await c.from('liderancas').select('*').order('nome');leaders=r.data||[];}catch(_){leaders=[];}}
async function openWhatsAppDialog(){if(!document.getElementById('vf-d-wa-dialog'))buildWhatsAppDialog();await loadLeaders();fillLeaderOptions();document.getElementById('vf-d-wa-dialog').classList.add('show');}
function buildWhatsAppDialog(){var d=dialog('vf-d-wa-dialog','WhatsApp','<div class="vf-d-field"><label>Escolha a liderança</label><select id="vfDWALeader"><option value="">Carregando...</option></select></div><div class="vf-d-wa-leader" id="vfDWAInfo">Selecione uma liderança cadastrada ou escolha “Outro número”.</div><div class="vf-d-field" id="vfDWAManualWrap" style="display:none"><label>Número com DDD</label><input id="vfDWANumber" placeholder="(43) 99999-9999"></div><div class="vf-d-presets"><button data-template="reuniao">Reunião</button><button data-template="convite">Convite</button><button data-template="lembrete">Lembrete</button><button data-template="agradecimento">Agradecimento</button></div><div class="vf-d-field"><label>Mensagem</label><textarea id="vfDWAMessage" placeholder="Digite ou escolha uma mensagem rápida..."></textarea></div><button class="vf-d-wa-open" id="vfDWAOpen">Abrir conversa no WhatsApp</button><div style="margin-top:8px;color:#6f86a2;font-size:9px;line-height:1.4">O VotoForte prepara a conversa, mas não envia nada sozinho. Você revisa e confirma o envio no WhatsApp.</div>',true);d.querySelectorAll('[data-template]').forEach(function(b){b.onclick=function(){var l=currentLeader();document.getElementById('vfDWAMessage').value=template(b.dataset.template,l);};});document.getElementById('vfDWALeader').onchange=syncWA;document.getElementById('vfDWAOpen').onclick=sendWA;}
function fillLeaderOptions(){var s=document.getElementById('vfDWALeader');if(!s)return;s.innerHTML='<option value="">Selecione uma liderança</option>'+leaders.map(function(l){return '<option value="'+esc(l.id)+'">'+esc([l.nome||'Liderança',l.bairro].filter(Boolean).join(' • '))+'</option>';}).join('')+'<option value="__manual__">Outro número</option>';syncWA();}
function currentLeader(){var s=document.getElementById('vfDWALeader'),id=s&&s.value;if(!id||id==='__manual__')return null;return leaders.find(function(l){return String(l.id)===String(id);})||null;}
function syncWA(){var s=document.getElementById('vfDWALeader'),v=s.value,l=currentLeader(),m=document.getElementById('vfDWAManualWrap'),i=document.getElementById('vfDWAInfo');m.style.display=v==='__manual__'?'block':'none';if(l){var p=l.whatsapp||l.telefone||l.celular||'';i.innerHTML='<strong>'+esc(l.nome||'Liderança')+'</strong><br>'+esc([l.bairro,p].filter(Boolean).join(' • ')||'WhatsApp não informado');}else i.textContent=v==='__manual__'?'Informe o número abaixo.':'Selecione uma liderança cadastrada ou escolha “Outro número”.';}
function sendWA(){var s=document.getElementById('vfDWALeader'),l=currentLeader(),phone=l&&(l.whatsapp||l.telefone||l.celular)||'';if(s.value==='__manual__')phone=document.getElementById('vfDWANumber').value;if(!s.value){alert('Escolha uma liderança ou selecione “Outro número”.');return;}var n=normalizeBR(phone);if(!n){alert('Informe um WhatsApp válido com DDD.');return;}var msg=document.getElementById('vfDWAMessage').value.trim();window.open('https://wa.me/'+n+(msg?'?text='+encodeURIComponent(msg):''),'_blank','noopener');}

var tries=0,t=setInterval(function(){tries++;if(buildShell()||tries>80)clearInterval(t);},100);
})();